---
- name: Configure Hosts File
  hosts: cassandraone
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: Update the /etc/hosts file with node name
    become: yes
    become_user: root
    lineinfile:
        path: "/etc/hosts"
        regexp: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ hostvars[item]['inventory_hostname']}}"
        state: present
        backup: yes
    register: etchostsupdate
    when: ansible_hostname != item or ansible_hostname == item
    with_items: "{{groups['cassandraone']}}"

- name: Configure Cassandra Nodes
  hosts: cassandraone
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  roles:
  - role: common
    when: ansible_distribution == 'CentOS' and (ansible_distribution_version == '7.7' or ansible_distribution_version == '7.8') 
  - role: cassandraone
    when: ansible_distribution == 'CentOS' and (ansible_distribution_version == '6.4' or ansible_distribution_version == '7.8')
