variable "project_suffix" {}
variable "environment" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "server_name" {}
variable "aws_ami" {}
variable "aws_type" {}
variable "node_count" {}
variable "root_disk_size" {}
variable "security_group" {}
