---
- name: Repository | Update Cassandra Repository
  copy:
    src: "cassandra.repo"
    dest: "/etc/yum.repos.d/cassandra.repo"
  register: cassandra_repo

- name: Install | Install Cassandra
  yum:
     name: "cassandra"
     state: present
  when:
  - ansible_os_family == 'RedHat'

- name: Folder Status | Get folder Status for cassandra.
  stat:
     path: "/etc/cassandra-org"
  register: cassandra_folder

- name: Create | Create Backup folder /etc/cassandra-org
  file:
     path: "/etc/cassandra-org"
     state: directory
     mode: 0755
     group: root
     owner: root
  when: cassandra_folder.stat.exists == false
  become: true 

- name: Create | Create Backup folder /etc/cassandra-org
  copy:
     src: "/etc/cassandra/"
     dest: "/etc/cassandra-org"
     remote_src: yes
  when: cassandra_folder.stat.exists == false
  become: true 

- name: Service | Stop Cassandra service
  systemd:
     name: cassandra
     enabled: yes
     state: stopped
     daemon_reload: yes

- name: Listing | Get directory listing
  find:
    path: "/var/lib/cassandra/data/system/" 
    file_type: any
    hidden: yes
  register: directory_content_result

- name: Delete | Remove directory content
  file:
    path: "/var/lib/cassandra/data/system/" 
    state: absent
  with_items: "{{ directory_content_result.files }}" 
  loop_control:
    label: "{{ item.path }}" 

- name: Update | Update /etc/security/limits.conf 
  lineinfile: 
    dest: "/etc/security/limits.conf"
    line: '{{ item }}'
  with_items:
    - 'elasticsearch soft nofile 65536'
    - 'elasticsearch hard nofile 65536'
    - 'elasticsearch soft memlock unlimited' 
    - 'elasticsearch hard memlock unlimited'

- name: Update | Update /etc/sysctl.conf 
  lineinfile:
    dest: "/etc/sysctl.conf"
    line: '{{ item }}'
  with_items:
    - 'vm.max_map_count = 262144'
    - 'net.ipv6.conf.all.disable_ipv6 = 1'
    - 'net.ipv6.conf.default.disable_ipv6 = 1'
    - 'net.ipv6.conf.lo.disable_ipv6 = 1'

- name: RackDC | Update RACK DC
  template:
    src: "cassandra-rackdc.properties.j2"
    dest: "/etc/cassandra/conf/cassandra-rackdc.properties"

- name: Update | Update Cluster Name in /etc/cassandra/default.conf/cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/default.conf/cassandra.yaml"
    regexp: "^cluster_name"
    line: "cluster_name: '{{ cluster_name }}'"

- name: Update | Update Listen Address in /etc/cassandra/default.conf/cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/default.conf/cassandra.yaml"
    regexp: "^listen_address"
    line: "listen_address: {{ inventory_hostname }}"

- name: Update | Update RPC Address in /etc/cassandra/default.conf/cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/default.conf/cassandra.yaml"
    regexp: "^rpc_address"
    line: "rpc_address: {{ inventory_hostname }}"

- name: Update | Update endpoint_snitch in /etc/cassandra/default.conf/cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/default.conf/cassandra.yaml"
    regexp: "^endpoint_snitch"
    line: "endpoint_snitch: GossipingPropertyFileSnitch"


- name: Update | Update - seeds in /etc/cassandra/default.conf/cassandra.yaml
  lineinfile:
    path: "/etc/cassandra/default.conf/cassandra.yaml"
    regexp: "^          - seeds:"
    line: "             - seeds: \"{{ cassandra_cluster }}\""

- name: Service | Enable Cassandra service
  systemd:
     name: cassandra
     enabled: yes
     state: restarted
     daemon_reload: yes
