variable "project_suffix" {}
variable "environment" {}
variable "vpc_id" {}
variable "public_subnet_1_id" {}
variable "public_subnet_2_id" {}
variable "private_subnet_1_id" {}
variable "private_subnet_2_id" {}
variable "kubernetes_cluster_name" {}
variable "kubernetes_version" {}
variable "kubernetes_instance_type" {}
variable "kubernetes_desired_node_size" {}
variable "kubernetes_desired_node_max_size" {}
variable "kubernetes_desired_node_min_size" {}
variable "kubernetes_node_disk_size" {}
