---
- name: Update | Update all packages
  yum:
     name: '*'
     state: present

- name: Install Dev Tools |  'Development tools' package group
  yum:
    name: "@Development tools"


- name: Install | Base packages
  yum:
    name:
      - git 
      - pyOpenSSL
      - vim
      - wget   

- name: Install | JAVA Packages
  yum:
    name:
      - java-11-openjdk-devel
      - java-11-openjdk

- name: Check if EPEL repo is already configured.
  stat:
    path: "{{ epel_repofile_path }}"
  register: epel_repofile_result

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 10
  when: not epel_repofile_result.stat.exists

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Be sure firewalld is disabled
  systemd: 
    name: firewalld 
    enabled: no
  ignore_errors: yes

- name: Be sure firewalld is stopped
  systemd: 
    name: firewalld 
    state: stopped
  ignore_errors: yes

- name: Disable Selinux
  selinux:
    policy: targeted
    state: disabled
  ignore_errors: yes

